# bim/manager_panel.py
# Building manager overlay — ESCALATE triggers a real, signage-aware
# pathfinding evacuation.
#
# Path computation and cone animation now live entirely in
# bim/assembly_point.py (compute_signage_aware_evacuation_paths() +
# animate_evacuation_via_paths()) rather than being duplicated here.
# The previous local _build_simple_paths() used a fixed 3-hop guess
# (nearest corridor -> a hardcoded exit fallback -> assembly) with no
# awareness of current sign state at all. The new version is a real
# networkx shortest path per occupant that penalises any node the
# graph currently marks sign_blocked — the same property normal-
# operation movement already reacts to — so evacuating occupants
# genuinely route around whatever the signage is currently telling
# them to avoid, using data that's already real elsewhere in the
# project rather than a new rule invented just for escalation.

import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from bim.ifc_bridge import send_to_blender


def install_manager_panel():
    project_root = os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))
    ).replace("\\", "/")

    blender_code = "\n".join([
        "import bpy, sys, blf, gpu",
        "from gpu_extras.batch import batch_for_shader",
        "",
        f"ROOT = r'{project_root}'",
        "if ROOT not in sys.path: sys.path.insert(0, ROOT)",
        "",
        "# ── Remove old handler ────────────────────────────────────────",
        "_NS = bpy.app.driver_namespace",
        "if _NS.get('fs_handle'):",
        "    try:",
        "        bpy.types.SpaceView3D.draw_handler_remove(_NS['fs_handle'], 'WINDOW')",
        "    except Exception: pass",
        "_NS['fs_handle'] = None",
        "",
        "BTN = {",
        "    'e': {'x': 60, 'y': 120, 'w': 280, 'h': 50},",
        "    'r': {'x': 60, 'y': 58,  'w': 280, 'h': 50},",
        "}",
        "COL = {",
        "    'e':  (0.72, 0.05, 0.05, 0.93),",
        "    'eh': (0.95, 0.15, 0.15, 0.98),",
        "    'r':  (0.05, 0.50, 0.12, 0.93),",
        "    'rh': (0.08, 0.70, 0.18, 0.98),",
        "    'sh': (0, 0, 0, 0.38),",
        "}",
        "_hov = {'e': False, 'r': False}",
        "",
        "def _inside(b, mx, my):",
        "    return b['x'] <= mx <= b['x']+b['w'] and b['y'] <= my <= b['y']+b['h']",
        "",
        "def _rect(x, y, w, h, col):",
        "    try: shader = gpu.shader.from_builtin('UNIFORM_COLOR')",
        "    except Exception: return",
        "    verts = [(x,y),(x+w,y),(x+w,y+h),(x,y),(x+w,y+h),(x,y+h)]",
        "    batch = batch_for_shader(shader, 'TRIS', {'pos': verts})",
        "    shader.bind()",
        "    shader.uniform_float('color', col)",
        "    gpu.state.blend_set('ALPHA')",
        "    batch.draw(shader)",
        "    gpu.state.blend_set('NONE')",
        "",
        "def _text(t, x, y, sz=12, col=(1,1,1,1)):",
        "    blf.size(0, sz)",
        "    blf.color(0, col[0], col[1], col[2], col[3])",
        "    blf.position(0, x, y, 0)",
        "    blf.draw(0, str(t))",
        "",
        "def _draw():",
        "    b  = BTN",
        "    ce = COL['eh'] if _hov['e'] else COL['e']",
        "    cr = COL['rh'] if _hov['r'] else COL['r']",
        "    _rect(b['e']['x']+4, b['e']['y']-4, b['e']['w'], b['e']['h'], COL['sh'])",
        "    _rect(b['r']['x']+4, b['r']['y']-4, b['r']['w'], b['r']['h'], COL['sh'])",
        "    _rect(b['e']['x'], b['e']['y'], b['e']['w'], b['e']['h'], ce)",
        "    _rect(b['r']['x'], b['r']['y'], b['r']['w'], b['r']['h'], cr)",
        "    _rect(b['e']['x'], b['e']['y'], 5, b['e']['h'], (1, 0.3, 0.3, 0.9))",
        "    _rect(b['r']['x'], b['r']['y'], 5, b['r']['h'], (0.3, 1, 0.4, 0.9))",
        "    _text('ESCALATE TO ASSEMBLY POINT', b['e']['x']+14, b['e']['y']+20, sz=12)",
        "    _text('RESET ALL SIGNS TO CLEAR',   b['r']['x']+14, b['r']['y']+20, sz=12)",
        "",
        "# ── ESCALATE ──────────────────────────────────────────────────",
        "# Path computation and cone animation now live entirely in",
        "# bim/assembly_point.py — compute_signage_aware_evacuation_paths()",
        "# uses a real networkx shortest path per occupant, penalising any",
        "# node the graph currently marks sign_blocked (the same property",
        "# normal-operation movement already reacts to), and",
        "# animate_evacuation_via_paths() drives the walk at fixed speed.",
        "# This file no longer duplicates that logic locally.",
        "",
        "def _escalate():",
        "    import sys, importlib; sys.path.insert(0, ROOT)",
        "",
        "    # Blender's Python process stays alive across every",
        "    # phase1_setup.py run in this session — unlike the external",
        "    # calling scripts, which start fresh each time and always",
        "    # see the current file, Blender's sys.modules cache can hold",
        "    # an already-imported, now-stale version of a module edited",
        "    # since it was first imported this session. Force-reloading",
        "    # here means _escalate() always runs against whatever is",
        "    # CURRENTLY on disk, not whatever Blender happened to load",
        "    # the first time these modules were touched this session.",
        "    for _modname in ('sensors.building_graph', 'sensors.sensor_sim',",
        "                     'bim.room_geometry', 'bim.assembly_point'):",
        "        if _modname in sys.modules:",
        "            try: importlib.reload(sys.modules[_modname])",
        "            except Exception as _e: print(f'Reload warning ({_modname}): {_e}')",
        "",
        "    # Step 0 — release control from any baked fix_and_bake.py demo.",
        "    # If a scenario's keyframed animation is still active on the",
        "    # cones, fix_and_bake.py's external driving loop keeps calling",
        "    # frame_set() every ~0.08s, which forces Blender to snap each",
        "    # cone's .location back to its baked keyframe on every single",
        "    # call — directly fighting the evacuation timer's own writes",
        "    # to the same property at a similar frequency, which is what",
        "    # produces visible jitter/vibration instead of clean movement.",
        "    # The scene's frame_change_pre handler that drives the board",
        "    # and sign text/colour from the baked per-tick schedule has",
        "    # the same conflict, just less visually obvious as a colour",
        "    # flicker than as position jitter. Clearing both here means",
        "    # ESCALATE takes full, uncontested control regardless of",
        "    # whether it's pressed from phase1_setup.py (nothing to",
        "    # clear, harmless no-op), a live fix_and_bake.py demo, or",
        "    # live_agent_runner.py.",
        "    try:",
        "        import bpy",
        "        cleared = 0",
        "        for obj in bpy.data.objects:",
        "            if obj.name.startswith('Occupant_') and obj.animation_data:",
        "                obj.animation_data_clear()",
        "                cleared += 1",
        "        removed_handlers = 0",
        "        for fn in [f for f in bpy.app.handlers.frame_change_pre",
        "                  if f.__name__ == '_board_handler']:",
        "            bpy.app.handlers.frame_change_pre.remove(fn)",
        "            removed_handlers += 1",
        "        print(f'Released baked animation: {cleared} cones, '",
        "              f'{removed_handlers} board/sign handler(s)')",
        "    except Exception as e:",
        "        print(f'Baked-animation release warning: {e}')",
        "",
        "    # Step 1 — lower attractiveness",
        "    try:",
        "        from sensors.sensor_sim import set_room_attractiveness",
        "        from sensors.building_graph import BUILDING_GRAPH as G",
        "        for _, d in G.nodes(data=True):",
        "            if d.get('node_type') == 'room':",
        "                try: set_room_attractiveness(d['label'], 0.0)",
        "                except Exception: pass",
        "    except Exception as e:",
        "        print(f'Attractiveness error: {e}')",
        "",
        "    # Step 2 — signs red (one Blender call)",
        "    from bim.ifc_bridge import send_to_blender as _s",
        "    _s(r'''",
        "import bpy",
        "RED = (0.90, 0.05, 0.05, 1.0)",
        "for obj in bpy.data.objects:",
        "    if obj.name.startswith('SignPanel_') and obj.data and obj.data.materials:",
        "        nd = obj.data.materials[0].node_tree.nodes.get('Principled BSDF')",
        "        if nd:",
        "            nd.inputs['Base Color'].default_value = RED",
        "            if 'Emission Color' in nd.inputs: nd.inputs['Emission Color'].default_value = RED",
        "            if 'Emission Strength' in nd.inputs: nd.inputs['Emission Strength'].default_value = 3.0",
        "    if obj.name.startswith('SignText_'):",
        "        obj.data.body = 'ESCALATED\\nProceed to\\nAssembly Point'",
        "for area in bpy.context.screen.areas:",
        "    if area.type == 'VIEW_3D': area.tag_redraw()",
        "print('Signs updated to RED')",
        "''')",
        "",
        "    # Step 3 — real signage-aware paths + fixed-speed walk,",
        "    # both now owned by bim/assembly_point.py. No sensor_sim",
        "    # snapshot here — this code runs inside Blender's own",
        "    # process, where a fresh sensor_sim import is always",
        "    # uninitialised/empty regardless of what phase1_setup.py,",
        "    # phase2_runner.py, or live_agent_runner.py did in their",
        "    # own separate processes. compute_signage_aware_evacuation_",
        "    # paths() resolves each cone's current room from its real,",
        "    # live position in the Blender scene instead.",
        "    #",
        "    # Diagnostics written to the FireSafetyBoard itself, not just",
        "    # the system console, so a failure here is actually visible",
        "    # in the viewport rather than silent.",
        "    try:",
        "        import bpy, traceback",
        "        from bim.room_geometry import load_room_centroids",
        "        from bim.assembly_point import (",
        "            compute_signage_aware_evacuation_paths,",
        "            animate_evacuation_via_paths,",
        "        )",
        "",
        "        cone_count = sum(1 for o in bpy.data.objects",
        "                        if o.name.startswith('Occupant_'))",
        "",
        "        centroids = load_room_centroids()",
        "        paths, refuge_info = compute_signage_aware_evacuation_paths(centroids)",
        "",
        "        board = bpy.data.objects.get('FireSafetyBoard')",
        "",
        "        # Wheelchair users on F1-F3 stay on their own floor rather",
        "        # than evacuate via stairs — mirrors agent_walk.py's TS-04",
        "        # mobility_refuge behaviour and real ADB practice (standard",
        "        # fire escape stairs generally aren't usable by a non-",
        "        # ambulant wheelchair user; they wait at a refuge for",
        "        # assisted evacuation). A wheelchair user already on the",
        "        # ground floor evacuates normally — no stairs needed.",
        "        refuge_lines = []",
        "        for r in refuge_info:",
        "            short_floor = r['floor'].split(' ')[0]",
        "            refuge_lines.append(",
        "                f'ALERT: Wheelchair user awaiting')",
        "            refuge_lines.append(",
        "                f'assistance - {short_floor}')",
        "",
        "        if not paths:",
        "            already_evac = sum(1 for o in bpy.data.objects",
        "                              if o.name.startswith('Occupant_')",
        "                              and o.get('fs_evacuated', False))",
        "            if already_evac >= cone_count and cone_count > 0:",
        "                msg = (f'ESCALATED\\n'",
        "                       f'All {cone_count} cones already at\\n'",
        "                       f'Assembly Point / refuge')",
        "                print(f'ESCALATE: nothing to do — all {cone_count} '",
        "                      f'cones already evacuated')",
        "            else:",
        "                msg = (f'ESCALATE: 0 paths computed\\n'",
        "                       f'{cone_count} cones found in scene\\n'",
        "                       f'Check console for details')",
        "                print(f'ESCALATE WARNING: {cone_count} cones found but 0 paths computed')",
        "            if board: board.data.body = msg",
        "        else:",
        "            animate_evacuation_via_paths(paths)",
        "            evac_count = len(paths) - len(refuge_info)",
        "            msg_lines = [",
        "                'ESCALATED',",
        "                f'{evac_count}/{cone_count} cones walking',",
        "                'to Assembly Point',",
        "            ] + refuge_lines",
        "            msg = '\\n'.join(msg_lines)",
        "            print(f'Signage-aware evacuation started: '",
        "                  f'{evac_count}/{cone_count} evacuating, '",
        "                  f'{len(refuge_info)} at refuge')",
        "            if board: board.data.body = msg",
        "",
        "    except Exception as e:",
        "        err_type = type(e).__name__",
        "        print(f'Evacuation path error [{err_type}]: {e}')",
        "        print(traceback.format_exc())",
        "        try:",
        "            import bpy",
        "            board = bpy.data.objects.get('FireSafetyBoard')",
        "            if board:",
        "                board.data.body = (f'ESCALATE FAILED\\n'",
        "                                   f'{err_type}: {str(e)[:60]}\\n'",
        "                                   f'See Blender system console')",
        "        except Exception:",
        "            pass",
        "",
        "    print('Escalation triggered')",
        "",
        "# ── RESET ─────────────────────────────────────────────────────",
        "def _reset():",
        "    import os as _os",
        "    from bim.assembly_point import EVAC_ACTIVE_FLAG",
        "    try:",
        "        if _os.path.exists(EVAC_ACTIVE_FLAG):",
        "            _os.remove(EVAC_ACTIVE_FLAG)",
        "    except Exception:",
        "        pass",
        "    from bim.ifc_bridge import send_to_blender as _s",
        "    _s(",
        "        'import bpy\\n'",
        "        'GREEN = (0.05, 0.70, 0.15, 1.0)\\n'",
        "        'for obj in bpy.data.objects:\\n'",
        "        '    if obj.name.startswith(\"SignPanel_\") and obj.data and obj.data.materials:\\n'",
        "        '        nd = obj.data.materials[0].node_tree.nodes.get(\"Principled BSDF\")\\n'",
        "        '        if nd:\\n'",
        "        '            nd.inputs[\"Base Color\"].default_value = GREEN\\n'",
        "        '            if \"Emission Color\" in nd.inputs: nd.inputs[\"Emission Color\"].default_value = GREEN\\n'",
        "        '            if \"Emission Strength\" in nd.inputs: nd.inputs[\"Emission Strength\"].default_value = 1.5\\n'",
        "        '    if obj.name.startswith(\"SignText_\"):\\n'",
        "        '        obj.data.body = \"Status: CLEAR\\\\nAll routes open\"\\n'",
        "        '    if obj.name.startswith(\"Occupant_\") and \"fs_evacuated\" in obj:\\n'",
        "        '        del obj[\"fs_evacuated\"]\\n'",
        "        'for area in bpy.context.screen.areas:\\n'",
        "        '    if area.type==\"VIEW_3D\": area.tag_redraw()\\n'",
        "        'print(\"RESET: all signs GREEN, evacuation flags cleared\")\\n'",
        "    )",
        "    print('Reset complete')",
        "",
        "# ── Operators ─────────────────────────────────────────────────",
        "class FS_OT_click(bpy.types.Operator):",
        "    bl_idname = 'firesafety.click'",
        "    bl_label  = 'FS Click'",
        "    def invoke(self, ctx, ev):",
        "        mx, my = ev.mouse_region_x, ev.mouse_region_y",
        "        if _inside(BTN['e'], mx, my): _escalate(); return {'FINISHED'}",
        "        if _inside(BTN['r'], mx, my): _reset();    return {'FINISHED'}",
        "        return {'PASS_THROUGH'}",
        "",
        "class FS_OT_hover(bpy.types.Operator):",
        "    bl_idname = 'firesafety.hover'",
        "    bl_label  = 'FS Hover'",
        "    def invoke(self, ctx, ev):",
        "        mx, my = ev.mouse_region_x, ev.mouse_region_y",
        "        prev = (_hov['e'], _hov['r'])",
        "        _hov['e'] = _inside(BTN['e'], mx, my)",
        "        _hov['r'] = _inside(BTN['r'], mx, my)",
        "        if (_hov['e'], _hov['r']) != prev: ctx.area.tag_redraw()",
        "        return {'PASS_THROUGH'}",
        "",
        "class FS_OT_escalate(bpy.types.Operator):",
        "    bl_idname = 'firesafety.escalate'",
        "    bl_label  = 'Escalate'",
        "    def execute(self, ctx): _escalate(); return {'FINISHED'}",
        "",
        "class FS_OT_reset(bpy.types.Operator):",
        "    bl_idname = 'firesafety.reset_signs'",
        "    bl_label  = 'Reset Signs'",
        "    def execute(self, ctx): _reset(); return {'FINISHED'}",
        "",
        "class FS_PT_panel(bpy.types.Panel):",
        "    bl_label       = 'Building Manager'",
        "    bl_idname      = 'FS_PT_panel'",
        "    bl_space_type  = 'VIEW_3D'",
        "    bl_region_type = 'UI'",
        "    bl_category    = 'Fire Safety'",
        "    def draw(self, ctx):",
        "        l = self.layout",
        "        l.label(text='Click buttons bottom-left of viewport')",
        "        l.separator()",
        "        r = l.row(); r.scale_y = 2.0; r.alert = True",
        "        r.operator('firesafety.escalate', text='ESCALATE', icon='ERROR')",
        "        r2 = l.row(); r2.scale_y = 1.5",
        "        r2.operator('firesafety.reset_signs', text='RESET', icon='CHECKMARK')",
        "",
        "for cls in [FS_OT_click, FS_OT_hover, FS_OT_escalate,",
        "            FS_OT_reset, FS_PT_panel]:",
        "    try: bpy.utils.unregister_class(cls)",
        "    except Exception: pass",
        "    bpy.utils.register_class(cls)",
        "",
        "_NS['fs_handle'] = bpy.types.SpaceView3D.draw_handler_add(",
        "    _draw, (), 'WINDOW', 'POST_PIXEL')",
        "",
        "wm = bpy.context.window_manager",
        "kc = wm.keyconfigs.addon",
        "if kc:",
        "    km = kc.keymaps.new(name='3D View', space_type='VIEW_3D')",
        "    for kmi in list(km.keymap_items):",
        "        if kmi.idname.startswith('firesafety.'): km.keymap_items.remove(kmi)",
        "    km.keymap_items.new('firesafety.click',       'LEFTMOUSE', 'PRESS')",
        "    km.keymap_items.new('firesafety.hover',       'MOUSEMOVE', 'ANY')",
        "    km.keymap_items.new('firesafety.escalate',    'E', 'PRESS', shift=True)",
        "    km.keymap_items.new('firesafety.reset_signs', 'R', 'PRESS', shift=True)",
        "",
        "for area in bpy.context.screen.areas:",
        "    if area.type == 'VIEW_3D': area.tag_redraw()",
        "print('Fire Safety UI ready')",
        "print('  ESCALATE: paths saved to file, read by Blender timer')",
        "print('  Fixed-speed movement — cones clearly visible walking')",
    ])

    return send_to_blender(blender_code)


if __name__ == "__main__":
    print("Installing Fire Safety Manager Panel...")
    result = install_manager_panel()
    print(f"Result: {result}")